models/task.py
from extensions import db # Importamos la instancia de db

class Task(db.Model):
    __tablename__ = 'tasks' # Nombre de la tabla en la DB

    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.String(200), nullable=False)
    # 'user.id' se refiere al nombre de la tabla ('user') y su columna 'id'.
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return f'<Task {self.id}: {self.content}>'

models/user.py
from extensions import db # Importamos la instancia de db

from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model):
    __tablename__ = 'users' # Nombre de la tabla

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False) # Para almacenar el hash de la contraseña

    # Relación uno a muchos: Un usuario puede tener muchas tareas

    # 'Task' = nombre de la clase del modelo Task.
    # 'backref='user'' crea una propiedad 'user' en el objeto Task.
    # 'lazy=True' significa que las tareas relacionadas se cargan solo cuando se acceden.
    tasks = db.relationship('Task', backref='user', lazy=True)

    def __repr__(self):
        return f'<User {self.username}>'

    # Métodos para manejar contraseñas de forma segura
    def setPassword(self, password):
        self.password_hash = generate_password_hash(password)

    def checkPassword(self, password):
        return check_password_hash(self.password_hash, password)

app.py
from flask import Flask, render_template
from extensions import db
from config import Config

# 1 ---- Inicializacion de la app ---- #
app = Flask(__name__)

# 2 ---- Carga de configuracion ---- #
app.config.from_object(Config)

# 3 ---- Inicializacion de la base de datos ---- #
db.init_app(app)

# 4 ---- Registro de rutas ---- #
from routes.auth import authBP
from routes.main import mainBP

app.register_blueprint(authBP)
app.register_blueprint(mainBP)

# 5 ---- Manejo de errores ---- #
@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

@app.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

if __name__ == '__main__':
    with app.app_context():
        # Creamos las tablas de la db si no existen
        db.create_all() 

    # Inicia el servidor de desarrollo
    app.run(debug=True)

routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session

from extensions import db # Importamos la instancia de db
from models.user import User

# Creamos un blueprint para las rutas
authBP = Blueprint('auth', __name__)

@authBP.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        # Validacion de datos
        if not username or not password:
            flash('Completa todos los campos.', 'error')
            return redirect(url_for('auth.register'))

        # Verificamos si existe el user
        existingUser = User.query.filter_by(username=username).first()

        if existingUser:
            flash('Nombre de usuario en uso', 'error')
            return redirect(url_for('auth.register'))

        # Crear nuevo usuario
        newUser = User(username=username)
        newUser.setPassword(password)

        # Guardar el nuevo user
        db.session.add(newUser)
        db.session.commit()

        flash('Registro exitoso!', 'success')
        return redirect(url_for('auth.login'))

    return render_template('register.html')


@authBP.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User.query.filter_by(username=username).first()

        # Verificar credenciales
        if user and user.checkPassword(password):
            session['user_id'] = user.id

            flash('Inicio de sesion exitoso', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Usuario o contraseña incorrectos.', 'error')
            return redirect(url_for('auth.login'))

    return render_template('login.html')


@authBP.route('/logout')
def logout():
    session.pop('user_id', None)

    flash('Cierre de sesion exitoso', 'info')
    return redirect(url_for('main.home'))

routes/main.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from extensions import db
from models.task import Task
from models.user import User

mainBP = Blueprint('main', __name__)

@mainBP.route('/')
def home():
    user = None
    tasks = []

    if 'user_id' in session:
        userId = session['user_id']
        user = User.query.get(userId)

        if user:
            tasks = user.tasks
        else:
            session.pop('user_id', None)
            flash('Inicia sesion', 'error')

    return render_template('home.html', tasks=tasks, user=user)


@mainBP.route('/task', methods=['POST'])
def createTask():
    if 'user_id' not in session:
        flash('Debes iniciar sesion para añadir tareas', 'error')
        return redirect(url_for('auth.login'))

    newTask = request.form.get('task')
    userId = session['user_id']

    if newTask:
        task = Task(content=newTask, user_id=userId)
        db.session.add(task)
        db.session.commit()
        flash('Tarea agregada exitosamente', 'success')
    else:
        flash('El nombre de la tarea es requerido', 'error')

    return redirect(url_for('main.home'))


@mainBP.route('/task/delete/<int:taskId>', methods=['POST'])
def deleteTask(taskId):
    if 'user_id' not in session:
        flash('Tenes que iniciar sesion para eliminar tareas', 'error')
        return redirect(url_for('auth.login'))

    userId = session['user_id']
    taskToDelte = Task.query.filter_by(id=taskId, user_id=userId).first()

    if taskToDelte:
        db.session.delete(taskToDelte)
        db.session.commit()
        flash('Tarea eliminada', 'success')
    else:
        flash('No se pudo eliminar la tarea', 'error')
    
    return redirect(url_for('main.home'))

templates/base.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>TO-DO App</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
    />
  </head>
  <body class="container mt-5">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
      <a class="navbar-brand" href="{{ url_for('main.home') }}">
        <img
          src="{{ url_for('static', filename='images/icon.png') }}"
          alt="Logo App"
          height="30"
          class="d-inline-block align-text-top me-2"
        />
        To-Do App
      </a>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">
          {% if session.user_id %}
          <li class="nav-item">
            <a
              class="nav-link btn btn-outline-danger btn-sm"
              href="{{ url_for('auth.logout') }}"
              >Cerrar Sesión</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a
              class="nav-link btn btn-outline-primary btn-sm me-2"
              href="{{ url_for('auth.login') }}"
              >Iniciar Sesión</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link btn btn-outline-success btn-sm"
              href="{{ url_for('auth.register') }}"
              >Registrarse</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
    <div class="mt-3">
      {% for category, message in messages %}
      <div
        class="alert alert-{{ 'success' if category == 'success' else 'danger' if category == 'error' else 'info' }}"
        role="alert"
      >
        {{ message }}
      </div>
      {% endfor %}
    </div>
    {% endif %} {% endwith %} {% block content %} {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %} {% block title %}Inicio{% endblock %} {% block
content%} {% if user %}
<h1>Mis tareas</h1>
<form method="POST" action="{{ url_for('main.createTask') }}" class="mb-3">
  <input
    name="task"
    type="text"
    id="task"
    class="form-control"
    placeholder="Nueva tarea"
    required
  />
  <button class="btn btn-primary mt-2">Agregar</button>
</form>
{% else %}
<p>
  Por favor, <a href="{{ url_for('auth.login') }}">inicia sesión</a> o
  <a href="{{ url_for('auth.register') }}">regístrate</a> para empezar a añadir
  tareas.
</p>
{% endif %} {% if user %}
<ul class="list-group">
  {% if tasks|length == 0 %}
  <li class="list-group-item">No hay tareas pendientes.</li>
  {% else %}
  <li class="list-group-item">Tareas pendientes:</li>
  {% for task in tasks %}
  <li class="list-group-item d-flex justify-content-between">
    {{ task.content }} {# Accedemos al atributo 'content' del objeto Task #}
    <form
      method="POST"
      action="{{ url_for('main.deleteTask', taskId=task.id) }}"
    >
      <button type="submit" class="btn btn-sm btn-danger">Eliminar</button>
    </form>
  </li>
  {% endfor %} {% endif %}
</ul>
{% endif %} {% endblock %}

templates/login.html
{% extends "base.html" %} {% block title %}Iniciar Sesión{% endblock %} {% block
content %}
<h1>Iniciar Sesión</h1>
<form action="{{ url_for('auth.login') }}" method="post">
  <div>
    <label for="username">Usuario:</label>
    <input
      type="text"
      id="username"
      name="username"
      class="form-control"
      required
    />
  </div>
  <div class="mt-3">
    <label for="password">Contraseña:</label>
    <input
      type="password"
      id="password"
      name="password"
      class="form-control"
      required
    />
  </div>
  <button type="submit" class="btn btn-primary mt-3">Entrar</button>
</form>
<p class="mt-3">
  ¿No tenes cuenta?
  <a href="{{ url_for('auth.register') }}">Regístrate aquí</a>.
</p>
{% endblock %}

templates/register.html
{% extends "base.html" %} {% block title %}Registrarse{% endblock %} {% block
content %}
<h1>Registrarse</h1>
<form action="{{ url_for('auth.register') }}" method="post">
  <div>
    <label for="username">Usuario:</label>
    <input
      type="text"
      id="username"
      name="username"
      class="form-control"
      required
    />
  </div>
  <div class="mt-3">
    <label for="password">Contraseña:</label>
    <input
      type="password"
      id="password"
      name="password"
      class="form-control"
      required
    />
  </div>
  <button type="submit" class="btn btn-success mt-3">Registrar</button>
</form>
<p class="mt-3">
  ¿Ya tienes cuenta?
  <a href="{{ url_for('auth.login') }}">Inicia sesión aquí</a>.
</p>
{% endblock %}